name: Build Mara - Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  MaraLib-build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore Mara.Lib
    - name: Build
      run: dotnet build --no-restore Mara.Lib
    - name: Test
      run: dotnet test --no-build --verbosity normal
  MaraGenerator-build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore Mara.Generator
    - name: Build
      run: dotnet build --no-restore Mara.Generator
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Mara.Generator
        path: Mara.Generator/bin/debug/net6.0-windows/

  MaraPS3Decryptor-build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore Mara.PS3.Decryptor
    - name: Build
      run: dotnet build --no-restore Mara.PS3.Decryptor
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Mara.PS3.Decryptor
        path: Mara.PS3.Decryptor/bin/debug/net6.0/
